### ISSUE TITLE
Missing block command

### ISSUE THREAD

**Issue by MikaelElkiaer** [arjunmahishi/flow.nvim#15]
Heya, love this plugin, especially after the refactor.

I just noticed that the block command is missing - or at least wasn't renamed.
There is a command defined as `command! RunCodeBlock lua require('flow').run_block()`, but I'd assume there should be a command `FlowRunBlock`.

**Comment by arjunmahishi** [comment]
Hey @MikaelElkiaer,

Thanks for you kind words!

Yes. This command was purposely not ported to the new scheme. I didn't there was any real use case for it. But if its something you are using, will be happy to port that as well. 

Can add this as a new command on the coming weekend. Or if you can raise a PR, that would be amazing!

Thanks

**Comment by MikaelElkiaer** [comment]
@arjunmahishi No problem, love how many possibilities are out there to customize your developer experience. :)

I will have a look once the need arises. :)

**Comment by arjunmahishi** [comment]
This is fixed in https://github.com/arjunmahishi/flow.nvim/commit/87c0e2ae173d520f5046eeaadf3478157c94c24d
