### ISSUE TITLE
E5108 when run custom cmd

### ISSUE THREAD

**Issue by lvim-tech** [arjunmahishi/flow.nvim#17]
Error executing lua: ...lov/.local/share/nvim/lazy/flow.nvim/lua/flow/output.lua:37: Invalid window id: 1010

**Comment by arjunmahishi** [comment]
@lvim-tech Can you give me more information?

1. Have you enabled the buffer in the output config? (maybe provide your entire config)
2. Version of neovim
3. If possible, steps to reproduce this error

**Comment by arjunmahishi** [comment]
I've noticed some issues that occur when you manually play around with the position of the output buffer after it opens. Will be able to comment/help more, if I have the above information.

**Comment by lvim-tech** [comment]
NVIM v0.10.0-dev-1298+g6823fdb20
```
        require("flow").setup({
            output = {
                buffer = true,
                split_cmd = "20split",
            },
            filetype_cmd_map = {
                python = "python3 <<-EOF\n%s\nEOF",
            },
        })
```
Just run `:FlowRunCustomCmd <alias>`

Thanks, @arjunmahishi

**Comment by lvim-tech** [comment]
Another problem - `:FlowLauncher` not open a new buffer to write and save command

**Comment by lvim-tech** [comment]
Yes, when comment `split_cmd = "20split"` - not E5108 error, but FlowLauncher not open a new buffer to write and save command.
Without comment `split_cmd = "20split"` - error E5108, but FlowLauncher open a new buffer to write and save command.

**Comment by arjunmahishi** [comment]
> Another problem - `:FlowLauncher` not open a new buffer to write and save command

Running this command will only launch the telescope interface. Once that it open, you will have to either edit an existing command (by pressing ctrl+e on it) or create a new one (by typing a non-existing command name). [More here](https://github.com/arjunmahishi/flow.nvim/wiki/Flow-launcher).

---

> when comment split_cmd = "20split" - not E5108 error [...]

Oh, interesting. I think the behavior of the split command might be different for you. Not sure why though. Maybe some other plugin is mutating the buffer_id. Not sure. I'll look into this more.

**Comment by lvim-tech** [comment]
```
return {
  handle_output = handle_output,
  reset_output_win = reset_output_win,
  show_last_output = show_last_output,
}
```
Where do you use `reset_output_win`
I think the problem is `if output_win == nil then`
