### ISSUE TITLE
Python does not properly interpolate

### ISSUE THREAD

**Issue by naquad** [arjunmahishi/flow.nvim#36]
NeoVIM v0.9.5
flow.nvim: master

The interpolation seems broken when trying to run Python scripts.

A case:

```lua
  {
    'arjunmahishi/flow.nvim',
    opts = {
      output = {
        buffer = true,
        size = 80,
        focused = true,
        modifiable = false,
      },

      filetype_cmd_map = {
        python = [[echo "cd $pwd && python $curr_file"]], -- same for echo cd $pwd && echo python $curr_file
      }
    },
    config = true,
    cmd = { 'FlowRunFile' },
    keys = {
      {'<leader>R', ':FlowRunFile<CR>'},
      {'<leader>cR', ':FlowRunCustomCmd<CR>'},
      {'<leader>cL', ':FlowLauncher<CR>'},
    }
  },
```

Command:
```
nvim test.py
```

Expected:

```
cd /home/naquad/projects/tests && python3 test.py
```

Actual:

```
cd  && python 
```

Other languages, such as Go, Rust, and Bash are working as expected.

**Comment by arjunmahishi** [comment]
Ahh... Thanks for pointing this out. The interpolation does not happen for the `:FlowRunFile` command at all (not sure how you got it working for Go, Rust, and Bash 🤔 ). Currently, the interpolation only happens while running custom commands. 

```lua
        filetype_cmd_map = {
          python = [[echo "cd $pwd && python $curr_file"]],
          go = [[echo "cd $pwd && go run $curr_file"]]
        }
```
I tried this and they both don't work.

---

But your use case makes sense to me. I will push a commit that adds interpolation for all types of commands.

**Comment by arjunmahishi** [comment]
Feel free to reopen this issue if you want to discuss anything more. Thanks again! :)

**Comment by naquad** [comment]
For rust it is "cargo run" so no interpolation needed, no idea how it was working for go. After the update it works as expected :+1:  Thanks.
